### ISSUE TITLE
为什么最底部的label与tableview之间有间隙？

### ISSUE THREAD

**Issue by l12ab** [MakeZL/ZLSwiftRefresh#1]
在demo里，前三个演示，最底部的“已经加载完”和上面的tableview有大约20的间隙；第四个演示里，该label还与底部有20的间隙，看了半天代码，没找到这个在哪里出现的。

另外，好像代码里有几处写的不对 比如 self.frame.height    掉了个size
另外，我想实现，全部上拉全部加载完毕后，隐藏底部的这个label

求指导，谢谢

**Comment by MakeZL** [comment]
抱歉，忘了说了，已经解决

**Comment by l12ab** [comment]
下次测试，谢谢回复
